
[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
edition = "2024"
version = "0.0.1"
license = "UNLICENSED"
repository = "https://github.com/scsmithr/vex"

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1
strip = true

[workspace.lints.clippy]
literal_string_with_formatting_args = "warn"

[workspace.dependencies]
vex_core = { path = "crates/vex_core" }
vex_editor = { path = "crates/vex_editor" }
vex_syntax = { path = "crates/vex_syntax" }
vex_term = { path = "crates/vex_term" }
vex_lsp = { path = "crates/vex_lsp" }
vex_git = { path = "crates/vex_git" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = "2.5"
libc = "0.2"
tree-sitter = "0.27"
tree-sitter-rust = "0.24.2"
tree-sitter-md = { version = "0.5.3", default-features = false }
tree-sitter-bash = "0.25.1"
tree-sitter-javascript = "0.25.0"
tree-sitter-typescript = "0.23.2"
crossterm = "0.29"
tempfile = "3.27"
signal-hook = "0.3.18"
ropey = "1.6.1"
regex-automata = { version = "0.4.18", default-features = false, features = ["std", "syntax", "unicode", "nfa-thompson", "dfa-build", "dfa-search"] }
unicode-segmentation = "1.13.3"
unicode-width = "0.2.2"
criterion = { version = "0.8", default-features = false, features = ["cargo_bench_support"] }
proptest = "1"
