
[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
edition = "2024"
version = "0.0.1"
license = "UNLICENSED"
repository = "https://github.com/scsmithr/vex"

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1
strip = true

[workspace.lints.clippy]
literal_string_with_formatting_args = "warn"

[workspace.dependencies]
vex_core = { path = "crates/vex_core" }
vex_editor = { path = "crates/vex_editor" }
vex_term = { path = "crates/vex_term" }
crossterm = "0.29"
tempfile = "3.27"
signal-hook = "0.3.18"
ropey = "1.6.1"
unicode-segmentation = "1.13.3"
unicode-width = "0.2.2"
criterion = { version = "0.8", default-features = false, features = ["cargo_bench_support"] }
proptest = "1"
