[package]
name = "vex_core"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ropey.workspace = true

[dev-dependencies]
criterion.workspace = true
proptest.workspace = true

[[bench]]
name = "editing"
harness = false

[lints]
workspace = true
