[package]
name = "vex_core"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ropey.workspace = true
unicode-segmentation.workspace = true
unicode-width.workspace = true
regex-automata.workspace = true

[dev-dependencies]
criterion.workspace = true
proptest.workspace = true
regex-automata = { workspace = true, features = ["meta"] }

[[bench]]
name = "editing"
harness = false

[[bench]]
name = "search"
harness = false

[lints]
workspace = true
