[package]
name = "vex_editor"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
vex_core.workspace = true

[dev-dependencies]
criterion.workspace = true
proptest.workspace = true

[[bench]]
name = "commands"
harness = false

[lints]
workspace = true
