[package]
name = "vex_lsp"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
vex_core.workspace = true
vex_editor.workspace = true
serde.workspace = true
serde_json.workspace = true
url.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
